spring:
  jpa:
      database: postgresql
      show-sql: false
      hibernate:
        ddl-auto: update
  
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost/consulta_medica
      username: postgres
      password: postgres
  
    data:
      mongodb:
        uri: mongodb+srv://70691210:SuperFranco3@cluster0.tulaodw.mongodb.net/?retryWrites=true&w=majority
        database: test
